# Generated by Django 5.0.7 on 2024-08-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookreview_author_remove_bookreview_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carditem',
            name='user',
        ),
        migrations.AddField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_items', to='books.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='items',
            field=models.ManyToManyField(related_name='cards', to='books.carditem'),
        ),
    ]
